### ISSUE TITLE
Support HARFBUZZ and Cairo for ligature

### ISSUE THREAD

**Issue by mikelxc** [d12frosted/homebrew-emacs-plus#276] opened 2020-11-16 16:27 UTC
Emacs-plus doesn't come with ligature support. 
While searching for enabling methods, I've found out that Mac port of Emacs (by Mitsuharu Yamamoto) for macOS has this enabled by default with (mac-auto-operator-composition-mode)
And there's a [ligature.el](https://github.com/mickeynp/ligature.el) which requires HARFBUZZ, and cairo. Both of them are not supported by emacs-plus@27 by default.

**Comment by mikelxc** [comment] 2020-11-16 16:29
related issue #222

**Comment by mikelxc** [comment] 2020-11-16 16:34
Work arounds, 
Add
`(when (window-system)
  (set-frame-font "Fira Code"))
(let ((alist '((33 . ".\\(?:\\(?:==\\|!!\\)\\|[!=]\\)")
               (35 . ".\\(?:###\\|##\\|_(\\|[#(?[_{]\\)")
               (36 . ".\\(?:>\\)")
               (37 . ".\\(?:\\(?:%%\\)\\|%\\)")
               (38 . ".\\(?:\\(?:&&\\)\\|&\\)")
               (42 . ".\\(?:\\(?:\\*\\*/\\)\\|\\(?:\\*[*/]\\)\\|[*/>]\\)")
               (43 . ".\\(?:\\(?:\\+\\+\\)\\|[+>]\\)")
               (45 . ".\\(?:\\(?:-[>-]\\|<<\\|>>\\)\\|[<>}~-]\\)")
               (46 . ".\\(?:\\(?:\\.[.<]\\)\\|[.=-]\\)")
               (47 . ".\\(?:\\(?:\\*\\*\\|//\\|==\\)\\|[*/=>]\\)")
               (48 . ".\\(?:x[a-zA-Z]\\)")
               (58 . ".\\(?:::\\|[:=]\\)")
               (59 . ".\\(?:;;\\|;\\)")
               (60 . ".\\(?:\\(?:!--\\)\\|\\(?:~~\\|->\\|\\$>\\|\\*>\\|\\+>\\|--\\|<[<=-]\\|=[<=>]\\||>\\)\\|[*$+~/<=>|-]\\)")
               (61 . ".\\(?:\\(?:/=\\|:=\\|<<\\|=[=>]\\|>>\\)\\|[<=>~]\\)")
               (62 . ".\\(?:\\(?:=>\\|>[=>-]\\)\\|[=>-]\\)")
               (63 . ".\\(?:\\(\\?\\?\\)\\|[:=?]\\)")
               (91 . ".\\(?:]\\)")
               (92 . ".\\(?:\\(?:\\\\\\\\\\)\\|\\\\\\)")
               (94 . ".\\(?:=\\)")
               (119 . ".\\(?:ww\\)")
               (123 . ".\\(?:-\\)")
               (124 . ".\\(?:\\(?:|[=|]\\)\\|[=>|]\\)")
               (126 . ".\\(?:~>\\|~~\\|[>=@~-]\\)")
               )
             ))
  (dolist (char-regexp alist)
    (set-char-table-range composition-function-table (car char-regexp)
                          `([,(cdr char-regexp) 0 font-shape-gstring]))))`
to config.el to manually enable ligature for Fira code

**Comment by d12frosted** [comment] 2020-11-16 18:38
Hey,

It seems like this issue is duplicate of #222. So closing this one. Please let me know if you think that it should be reopened.

**Closed by d12frosted** 2020-11-16 18:38 UTC
Labels: feature request

**Comment by katafrakt** [comment] 2021-05-31 19:03
Sorry to dig up an old issue, but I think this one is not a duplicate of #222, as the other one is about porting mac-emacs's support for ligatures. Adding Harfbuzz support seems to be something a bit different, making ligatures work for most ligature-enabled fonts OOTB in Emacs 28.

I'm no expert though, I'm just compiling what I read in [ligature.el](https://github.com/mickeynp/ligature.el) and [doom emacs's ligatures](https://github.com/hlissner/doom-emacs/blob/develop/modules/ui/ligatures/README.org).

**Comment by elken** [comment] 2021-07-14 17:01
> Sorry to dig up an old issue, but I think this one is not a duplicate of #222, as the other one is about porting mac-emacs's support for ligatures. Adding Harfbuzz support seems to be something a bit different, making ligatures work for most ligature-enabled fonts OOTB in Emacs 28.
> 
> I'm no expert though, I'm just compiling what I read in [ligature.el](https://github.com/mickeynp/ligature.el) and [doom emacs's ligatures](https://github.com/hlissner/doom-emacs/blob/develop/modules/ui/ligatures/README.org).

Correct, it's set to be compiled in by default just needed some extra changes detailed in the linked PR
