### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by Kwask94** [d12frosted/homebrew-emacs-plus#95] opened 2018-09-19 20:49 UTC
Hello, I'm having rather strange problem while trying to emacs-plus. it gives me total blank screen
System - Mojave

![](https://preview.ibb.co/hTJxGe/Screen_Shot_2018_09_19_at_11_45_01_PM.png)

I've tried both version 25/26 and it get's me the same results. I use spacemacs

thanks

**Comment by d12frosted** [comment] 2018-09-20 04:38
Hi @Kwask94 ,

Sounds bad. I don't have Mojave on any of my computers yet, so I can't test it right away. Just a hint - try using `--HEAD` option during installation. Maybe there are fixes for new OS.

**Comment by amokan** [comment] 2018-09-23 00:45
FWIW - Same problem for me. OSX Mojave.

**Comment by bwl** [comment] 2018-09-24 20:35
Hit same problem on fresh install of Mojave. Tried reinstalling with `--HEAD` and issue unfortunately persists.

**Comment by d12frosted** [comment] 2018-09-25 04:33
I get messages that some people are using `emacs-plus` on Mojave without any problems.

I have two suggestions:

1. Install the latest Xcode and command line tools.
2. Reinstall `emacs-plus` (release version should be ok).

**Comment by dsdshcym** [comment] 2018-09-25 06:55
Hope these can help:
- http://emacs.1067599.n8.nabble.com/bug-31904-27-0-50-Emacs-doesn-t-render-text-modeline-Mac-OSX-10-14-Mojave-tt458613.html
- http://emacs.1067599.n8.nabble.com/bug-32812-27-0-50-macOS-Mojave-GNU-Emacs-crash-after-5-10-minutes-or-so-td465791.html

I added these two patches to `emacs-plus.rb` and the issue got fixed:

```
    patch do
      url "https://github.com/emacs-mirror/emacs/compare/scratch/ns-drawing.patch"
      sha256 "95aad40f90b3750858c700152d46d5bf5062f12c76d77dd838998c86301fdcb8"
    end

    patch do
      url "http://emacs.1067599.n8.nabble.com/attachment/465838/0/0001-Fix-crash-on-flush-to-display-bug-32812.patch"
    end
```

**Comment by ChrisBuchholz** [comment] 2018-09-26 15:44
Adding the patches

```
  patch do
      url "https://github.com/emacs-mirror/emacs/compare/scratch/ns-drawing.patch"
      sha256 "95aad40f90b3750858c700152d46d5bf5062f12c76d77dd838998c86301fdcb8"
    end

    patch do
      url "http://emacs.1067599.n8.nabble.com/attachment/465838/0/0001-Fix-crash-on-flush-to-display-bug-32812.patch"
    end
```

As [dsdshcym mentions](https://github.com/d12frosted/homebrew-emacs-plus/issues/95#issuecomment-424228332) and then installing with `--HEAD` seems to have fixed the problem for me as well.

**Comment by d12frosted** [comment] 2018-09-26 16:42
@fbkarsdorp thank you for checking. It's sad that it didn't work.

@dsdshcym nice! thank you very much! I will add these to formula. 

@ChrisBuchholz thanks for checking it! Does it work without HEAD?

**Comment by d12frosted** [comment] 2018-09-26 16:50
FYI, I have a PR with this change. Will update readme and info message to help Mojave users.

**Comment by d12frosted** [comment] 2018-09-26 17:18
Merged. Please use `--HEAD` option for installing `emacs-plus` on macOS Mojave.

Thanks everyone who reported this issue and everyone who helped to find a workaround. ❤️

**Closed** 2018-09-26 17:18 UTC
Labels: other

**Comment by aaronjensen** [comment] 2018-09-26 23:15
There's another patch to fix a deprecation warning: https://lists.gnu.org/archive/html/emacs-devel/2018-09/msg00934.html

**Comment by d12frosted** [comment] 2018-09-27 04:37
@aaronjensen looks good and not as big 😸 

Would be nice if someone could check that this only patch works well on Mojave (instead two we've added yesterday).

**Comment by aaronjensen** [comment] 2018-09-27 04:44
@d12frosted that one is only the second part (the first part is here, which is what I incorrectly assumed was applied here already: https://lists.gnu.org/archive/html/emacs-devel/2018-09/msg00931.html)

I tried to apply those two patches to `--HEAD` and they didn't apply. It's possible that I did something wrong or that they're intended for `emacs-26`. Either way, what's there now works fine for now and we can probably wait until the official patches are applied to the `emacs-26` branch (and then merged to `master`)

**Comment by d12frosted** [comment] 2018-09-27 04:46
@aaronjensen I see. Thank you very much for checking this out 😸 

I agree, let's wait for the official fixes.

**Comment by d12frosted** [comment] 2018-10-05 06:56
@aaronjensen thanks for linking it here. 

P. S. I haven't faced this issue yet.

**Comment by vyorkin** [comment] 2018-11-07 21:00
facing the same rendering issue as @aaronjensen, sometimes it just renders a blank screen

**Comment by afincato** [comment] 2018-12-01 17:15
been having the same blank screen problem when i installed `emacs-plus` with some options, eg

```
brew install emacs-plus --without-spacemacs-icon
```

if i just install `emacs-plus` with

```
brew install emacs-plus
```

everything runs smoothly on macOS Mojave (`10.14.1 `).

hope this can help!

**Comment by JamesMcMahon** [comment] 2019-01-19 03:14
I still hit the issue after running plain old,

    brew install emacs-plus

I see the following in the console on startup,

> 2019-01-18 21:11:57.577 Emacs[85077:4527086] Failed to initialize color list unarchiver: Error Domain=NSCocoaErrorDomain Code=4864 "*** -[NSKeyedUnarchiver _initForReadingFromData:error:throwLegacyExceptions:]: non-keyed archive cannot be decoded by NSKeyedUnarchiver" UserInfo={NSDebugDescription=*** -[NSKeyedUnarchiver _initForReadingFromData:error:throwLegacyExceptions:]: non-keyed archive cannot be decoded by NSKeyedUnarchiver}

**Comment by JamesMcMahon** [comment] 2019-01-19 16:44
I ended up just installing the emacs cask for now. I'll try again once this package is all caught up.

**Comment by RosalesJ** [comment] 2019-01-26 21:40
I had an old computer with Mojave and emacs-plus worked fine on it. When upgrading to a new computer this issue occurred and I've switched to emacs-mac for the time being (which I do have some problems with) until this issue is dealt with.

**Comment by otherjoel** [comment] 2022-11-19 20:17
In case anyone else runs into this issue, I found that for me the cause was that my `config.el` referred to fonts that were not installed on my new laptop. Removing/fixing those references fixed the issue immediately.
