### ISSUE TITLE
Could not install with [OPTIONS]

### ISSUE THREAD

**Issue by angelporo** [d12frosted/homebrew-emacs-plus#301] opened 2021-01-05 11:43 UTC
emacs@28 There will be a problem with key combos for a while, I hope it can be improved, but the performance is indeed much better

**Comment by d12frosted** [comment] 2021-01-05 11:54
@angelporo sorry, I don't understand your issue :smile_cat: can you please elaborate a little bit more? What were you trying to do? What exactly went wrong? That would be helpful :pray: 

In case you wanted to start a discussion, please use [new feature provided by GitHub][1]. 

  [1]: https://github.com/d12frosted/homebrew-emacs-plus/discussions

**Comment by d12frosted** [comment] 2021-01-07 08:04
Closing as it's not clear what the problem is. Please let me know if you think it's still relevant, but provide more information, so I can help.

**Closed by d12frosted** 2021-01-07 08:04 UTC
Labels: install error

**Comment by angelporo** [comment] 2021-01-07 08:58
Sorry, there is no problem at present. This problem is caused by multiple key clicks caused by the keyboard
