### ISSUE TITLE
Error: Invalid formula...stack level too deep

### ISSUE THREAD

**Issue by johnnypea** [d12frosted/homebrew-emacs-plus#348] opened 2021-04-28 15:51 UTC
```
brew tap d12frosted/emacs-plus
==> Tapping d12frosted/emacs-plus
Cloning into '/usr/local/Homebrew/Library/Taps/d12frosted/homebrew-emacs-plus'...
remote: Enumerating objects: 1808, done.
remote: Counting objects: 100% (241/241), done.
remote: Compressing objects: 100% (172/172), done.
remote: Total 1808 (delta 97), reused 207 (delta 69), pack-reused 1567
Receiving objects: 100% (1808/1808), 20.89 MiB | 1.85 MiB/s, done.
Resolving deltas: 100% (819/819), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/d12frosted/homebrew-emacs-plus/Formula/emacs-plus@28.rb
stack level too deep
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/d12frosted/homebrew-emacs-plus/Formula/emacs-plus@26.rb
stack level too deep
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/d12frosted/homebrew-emacs-plus/Formula/emacs-plus@27.rb
stack level too deep
Error: Cannot tap d12frosted/emacs-plus: invalid syntax in tap!
```

**Comment by d12frosted** [comment] 2021-04-28 15:52
Yup, see also on [CI](https://github.com/d12frosted/homebrew-emacs-plus/runs/2458892473?check_suite_focus=true).

Will try to fix ASAP.

**Comment by d12frosted** [comment] 2021-04-28 15:58
I reverted my changes. Should be good now. Will investigate the root cause and fix it without blocking you :)

**Comment by idcrook** [comment] 2021-04-28 16:00
works again for me

Note: another failure mode was:

```console
$ brew upgrade
Error: stack level too deep
/opt/homebrew/Library/Homebrew/formulary.rb:468:in `loader_for'
/opt/homebrew/Library/Homebrew/formulary.rb:374:in `factory'
/opt/homebrew/Library/Homebrew/formula.rb:1665:in `[]'
...
```

**Comment by d12frosted** [comment] 2021-04-28 16:28
It's interesting that `brew` loads the formula during the `tap` operation. And since I query `Formula[@formula_name]`, it makes things to go brrrrr. Alright, I need to move that somewhere.

**Comment by d12frosted** [comment] 2021-04-28 19:16
Ok, this is not my day. Sorry for breaking everyone. Reverted again.

**Comment by d12frosted** [comment] 2021-04-28 19:33
I think I fixed that. Since I need to test 'online' build (e.g. imitate fresh install without manual clone), I had to create a copy of this repo and test there. And it seems like it works - https://github.com/d12frosted/homebrew-emacs-plus-copy/runs/2460789630?check_suite_focus=true

Will merge tomorrow 🤔 Not going to risk today 😅

**Comment by d12frosted** [comment] 2021-04-29 06:48
🤦  CI passed there, but in reality I didn't fix anything. That's because I forgot to change the URL in tests 🤦 Indeed, yesterday was a bad day for me.

So I picked different approach. See #349 for more information.

**Comment by d12frosted** [comment] 2021-04-29 08:02
Merged! Let's see how it goes. 🤞

**Comment by d12frosted** [comment] 2021-04-29 10:04
Yup, builds. Closing this now. 🎉

**Closed by d12frosted** 2021-04-29 10:04 UTC
Labels: install error

**Comment by johnnypea** [comment] 2021-04-29 10:16
Thank you!
