### ISSUE TITLE
"'Emacs' would like to control this computer using accessibility features"

### ISSUE THREAD

**Issue by paulhenrich** [d12frosted/homebrew-emacs-plus#107] opened 2018-10-25 15:28 UTC
![screen shot 2018-10-24 at 8 49 54 pm](https://user-images.githubusercontent.com/919849/47511461-3b5d1100-d848-11e8-9414-eec0e4272613.png)

I just got this dialog on MacOS Mojave (10.14) with Emacs 26.1 (9.0) installed with `brew install emacs-plus` yesterday. It happened after clicking in the menu bar, but instead of the menu opening, it displayed this dialog. I have seen it once before on a previous version a couple days prior (which prompted me to uninstall, update, and reinstall the current version).

I don't know how to reproduce it (clicking the menu bar doesn't always result in this).

I of course clicked deny. It's a little alarming and I was wondering if anyone else has seen this or knows what's happening.

**Comment by bwolf** [comment] 2018-10-25 22:00
I have seen this also in various combinations (without interacting with the menu). Also Emacs requested access to contacts, calendars, photos, accessibility. I blamed so far Mojave, because these where present in High Sierra also. Emacs worked fine so far (beside some rendering issues which remain unsolved).

**Comment by d12frosted** [comment] 2018-10-26 18:03
Hi everyone,

These messages depend on your Emacs configurations. You are prompted once your code tries to do something that requires additional permissions/features. They changed this in Mojave and you can see many applications are now causing this kind of prompts to appear.

For example, if you open a `multi-term`(or something alike) in Emacs and run 

```
osascript -e 'if application "iTunes" is running then tell application "iTunes" to if player state is playing then return true'
```

You will be prompted to allow `Emacs.app` to control `iTunes.app`. After I give permission to do it, I see `Emacs` under automation scope in `System Preferences > Security & Privacy > Privacy`.

Many things can require accessibility features, but it depends on your configurations.

**Comment by bwolf** [comment] 2018-10-29 23:21
Thanks,

in my case I never do such things (afaik). But I do also see this issue in various other Apps like Dropbox (stopped recently) and also in JetBrains products. Sometimes is happens in Emacs when I use the menu (by accident with the mouse, I nearly never use the menu).

I guess what you describe has (maybe) something todo with full disk access, which is new in Mojave. My configuration lives mainly in ~/.emacs.d/ and what ever file I access in ~/, ~/Code or other typical directories.

It may also play a role what kind of user you use on the system. In my case, I'm not in the admin group (or whatever it is called).

**Comment by d12frosted** [comment] 2018-11-08 06:30
Once I give permissions, all other menus are opening on hover as well. 

BTW, I can reproduce this behaviour with other Emacs 'distributions' (e. g. building from sources on the master branch, a prebuilt app from emacsformacosx) without any custom configurations. There must be something about Emacs itself that asks for permissions.

**Comment by jassa** [comment] 2019-09-20 16:50
Related discussion: [emacs menu items require clicking twice](http://emacs.1067599.n8.nabble.com/bug-32864-26-1-menus-don-t-work-correctly-in-Mac-OS-Mojave-td466157.html) (accessibility permission fixes it)

**Comment by Blaisorblade** [comment] 2019-12-18 18:34
@jassa That probably explains it:

1. When you click on a menu, Emacs *synthesizes* a click (don't ask why, gory details in [this message](http://emacs.1067599.n8.nabble.com/bug-32864-26-1-menus-don-t-work-correctly-in-Mac-OS-Mojave-tp466157p485731.html)). The thread doesn't discuss hovering, but it's plausibly a related issue.
2. In their words: > In MacOS Mojave, synthetic mouse events are blocked for security reasons, so this no longer works; the synthetic click is discarded and the menu doesn't open.

**Comment by d12frosted** [comment] 2020-05-09 10:05
Thanks everyone for your responses and comments in this thread. Since it's stalled, I am going to close it. Feel free to continue discussion if you have anything to add 😸

**Closed by d12frosted** 2020-05-09 10:05 UTC
Labels: question
