### ISSUE TITLE
Could not install with --HEAD due to multifont patch application

### ISSUE THREAD

**Issue by wakatara** [d12frosted/homebrew-emacs-plus#209] opened 2020-05-03 14:55 UTC
**Describe the bug**

The build on HEAD appears to fail on the multicolor font patch (sad, cause was installing to get emoji support sorted.  =p ).

**Command used to install `emacs-plus`**

``` 
brew install emacs-plus --HEAD --with-emacs-27-branch --with-jansson
```

**Installation log**

```
 λ ~ brew install emacs-plus --HEAD --with-emacs-27-branch --with-jansson
Updating Homebrew...
==> Installing emacs-plus from d12frosted/emacs-plus
==> Cloning https://github.com/emacs-mirror/emacs.git
Updating /Users/daryl/Library/Caches/Homebrew/emacs-plus--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 6326825 Regexps cannot infloop; fix manual
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/patches/multicolor-fonts.patch
Already downloaded: /Users/daryl/Library/Caches/Homebrew/downloads/6e0bcfe5f86b21ca9f1bf349995832a6143baac4a74e000dff771b2839b6fa7d--multicolor-fonts.patch
==> Downloading https://raw.githubusercontent.com/d12frosted/homebrew-emacs-plus/master/patches/fix-window-role.patch
Already downloaded: /Users/daryl/Library/Caches/Homebrew/downloads/b7046a273c114e23f734df97967f4016486f1d080bad1ba40dbd53a5c86a09e0--fix-window-role.patch
==> Patching
==> Applying multicolor-fonts.patch
patching file src/macfont.m
Hunk #1 FAILED at 2373.
1 out of 1 hunk FAILED -- saving rejects to file src/macfont.m.rej
Error: Failure while executing; `patch -g 0 -f -p1 -i /private/tmp/emacs-plus--patch-20200503-67560-kjsewm/multicolor-fonts.patch` exited with 1.
```

**Comment by parhamdoustdar** [comment] 2020-05-03 15:39
Strangely enough, even adding `--without-multicolor-fonts` doesn't fix this for me?

**Comment by wakatara** [comment] 2020-05-03 15:58
> Strangely enough, even adding `--without-multicolor-fonts` doesn't fix this for me?

(embarassingly, I did not check trying not to install with that... ahem... )

**Comment by d12frosted** [comment] 2020-05-04 05:33
Hey, thank you very much for the report.

I don't quite understand why you are still on master even though you used `--with-emacs-27-branch` option.

```
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
```

This how it looks for me (I copied your options):

```
==> Checking out branch emacs-27
Switched to branch 'emacs-27'
Your branch is behind 'origin/emacs-27' by 32 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
HEAD is now at 4b419083f9 Honor search-upper-case
```

But then, I don't get `multicolor-fonts` patch applied to me 🤔 On CI it is also not applied in [HEAD][1] and on [Emacs27][2]. Even though by default this patch is enabled on all `HEAD` installs (e.g. on Emacs 27 as well).

Also, `--without-multicolor-fonts` should actually help you. @wakatara and @parhamdoustdar can you please share the output when installing with this option?

On a side note, sometimes I just don't get how brew works.

  [1]: https://github.com/d12frosted/homebrew-emacs-plus/runs/639990107?check_suite_focus=true#step:3:268
  [2]: https://github.com/d12frosted/homebrew-emacs-plus/runs/639990134?check_suite_focus=true#step:3:277

**Comment by d12frosted** [comment] 2020-05-04 05:46
I actually didn't read code carefully, so I made a mistake in my judgement.

```ruby
if build.with? "multicolor-fonts"
    unless build.head?
      patch do
        url (PatchUrlResolver.url "multicolor-fonts")
        sha256 "7597514585c036c01d848b1b2cc073947518522ba6710640b1c027ff47c99ca7"
      end
    end
  end
```

This patch is applied ONLY on Emacs 26.3 (e.g. when built without `--HEAD`). So it should not be applied on Emacs 27 as well. This is what I see locally and what I see on CI.

I am not sure why you get this patch. I wild guess would be that you are using `reinstall` instead of `uninstall` + `install`, but in the shared output I see that you are using `install`. So 🤷

**Comment by honuonhval** [comment] 2020-05-04 05:46
It looks like patch isn't needed on HEAD.  The "patch" is already applied to [emacs/macfont.m](https://github.com/emacs-mirror/emacs/blob/master/src/macfont.m#L2357).  I was able to compile with --HEAD by just commenting out the patch part

**Comment by d12frosted** [comment] 2020-05-04 05:50
Would be also lovely to have output of the following commands:

- `brew doctor`
- `brew config`

**Comment by d12frosted** [comment] 2020-05-04 05:53
> it may be another bug but "multicolor-fonts" is applied even when building with --HEAD. As I mentioned, I was able to build with (--HEAD --with-jansson --with-native-comp-branch) by commenting out the multicolor-font part and updating the sha256 for fix-window-role.patch

Yes, it sounds like a bug. The code clearly states that this patch must not be applied when building on `HEAD`. Why `brew` picks it up, I am not sure. 

Maybe it's differences in our env/config? So here is output of the mentioned commands on my machine:

```
$ brew config
HOMEBREW_VERSION: 2.2.14
ORIGIN: https://github.com/Homebrew/brew
HEAD: e2bc0fa6879ce4c74ea2d8f8c654c9812f776b43
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 46b41b27375cff5e875c26df9c7f3576e88eccc8
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.YAGwrukjae/org.macosforge.xquartz:0
HOMEBREW_EDITOR: emacsclient
HOMEBREW_MAKE_JOBS: 8
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.26.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 14.0.1
macOS: 10.15.4-x86_64
CLT: 11.4.1.0.1.1586360307
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  emacs-plus-local
  haskell-stack
```

**Comment by honuonhval** [comment] 2020-05-04 06:00
My brew config and doctor
```
$ brew config
HOMEBREW_VERSION: 2.2.14-62-g9befd55
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 9befd55d5e6c5557ce9d02fa97808505f5362c0d
Last commit: 16 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 46b41b27375cff5e875c26df9c7f3576e88eccc8
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_EDITOR: emacs -nw
HOMEBREW_MAKE_JOBS: 8
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.26.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 14, 11.0.7, 9.0.1, 1.8.0_152
macOS: 10.15.4-x86_64
CLT: N/A
Xcode: 11.4.1
```

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/honuonhval/.pyenv/shims/python-config
  /Users/honuonhval/.pyenv/shims/python3-config
  /Users/honuonhval/.pyenv/shims/python3.8-config

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  pngout
```

**Comment by d12frosted** [comment] 2020-05-04 06:12
When I do `brew update` and `brew upgrade` I don't get any changes in brew version. It seems that I am on the stable branch. Are you on `master`?

**Comment by d12frosted** [comment] 2020-05-04 06:14
Ok, I've manually reset my brew to the latest `master` and can reproduce this issue. It's an upstream bug and should be reported there. Might be related to https://github.com/Homebrew/brew/commit/92f26e991cefcf39adb5da861c6cce7b05f4dfad

**Comment by honuonhval** [comment] 2020-05-04 06:20
Ah, makes sense.  Just noticed my build was on `master` not `feature/native-comp`

**Comment by d12frosted** [comment] 2020-05-04 06:24
Ah sorry for the confusion, I mean the `homebrew` branch. E.g. in `/usr/local/Homebrew`.

AFAIK, they are doing some changes in argument parsing process and [sometimes][1] they break compatibility.

  [1]: https://github.com/Homebrew/brew/issues/7397

**Comment by d12frosted** [comment] 2020-05-04 09:00
Reported it here: https://github.com/Homebrew/brew/issues/7498

**Comment by d12frosted** [comment] 2020-05-04 11:00
Upstream issue was resolved via https://github.com/Homebrew/brew/commit/ae353ff42e6b5da042d82a51683f1e1ee6d8c8fe, so if you encountered it make sure to update the `brew` to the latest commit. 

Please let me know if it still doesn't work for you.

**Closed by d12frosted** 2020-05-04 11:00 UTC
Labels: install error, upstream issue: brew
