### ISSUE TITLE
Could not install emacs-plus@29

### ISSUE THREAD

**Issue by Cliffzz** [d12frosted/homebrew-emacs-plus#544] opened 2023-01-27 11:50 UTC
Please make sure to follow these steps (and mark the checkboxes):

- [x] run `brew update` and try to reproduce the issue again
- [x] run `brew doctor`, fix all issues and try to reproduce your issue again
- [x] run `brew config` and `brew doctor` and include their output

## What you were trying to do

Install emacs@29, emacs@28 and emacs@30 works fine, it might just be something upstream emacs.

## What happened (include command output)

<pre>
$ brew install emacs-plus@29
</pre>

<details>
  <summary>Command output</summary>
  <pre>

  ==> Fetching d12frosted/emacs-plus/emacs-plus@29
==> Cloning https://github.com/emacs-mirror/emacs.git
Updating /Users/cliffz/Library/Caches/Homebrew/emacs-plus@29--git
==> Checking out branch emacs-29
Already on 'emacs-29'
Your branch is up to date with 'origin/emacs-29'.
HEAD is now at f72a394716 Work around package.el transitive dependency bug
==> Installing emacs-plus@29 from d12frosted/emacs-plus
==> Patching
==> Applying fix-window-role.patch
patching file 'src/nsterm.m'
==> Applying system-appearance.patch
patching file 'src/frame.h'
patching file 'src/nsfns.m'
patching file 'src/nsterm.m'
==> Applying round-undecorated-frame.patch
patching file 'src/frame.c'
patching file 'src/frame.h'
patching file 'src/nsfns.m'
patching file 'src/nsterm.h'
patching file 'src/nsterm.m'
==> ./autogen.sh
==> ./configure --enable-locallisppath=/opt/homebrew/share/emacs/site-lisp --infodir=/opt/homebrew/Cellar/emacs-plus@29/29.0.60/share/info/emacs --prefix=/opt/homebrew/Cellar/emacs-plus@29/29.0.60 --with-xml2 --with-gnutls --
==> gmake
Last 15 lines from /Users/cliffz/Library/Logs/Homebrew/emacs-plus@29/03.gmake:
gmake[2]: Leaving directory '/private/tmp/emacs-plusA29-20230127-35677-rbj5nt/lisp'
gmake[1]: *** [Makefile:533: lisp] Error 2
gmake[1]: Leaving directory '/private/tmp/emacs-plusA29-20230127-35677-rbj5nt'
gmake[1]: Entering directory '/private/tmp/emacs-plusA29-20230127-35677-rbj5nt'
***
*** "make all" failed with exit status 2.
***
*** You could try to:
*** - run "make bootstrap", which might fix the problem
*** - run "make V=1", which displays the full commands invoked by make,
***   to further investigate the problem
***
gmake[1]: *** [Makefile:414: advice-on-failure] Error 2
gmake[1]: Leaving directory '/private/tmp/emacs-plusA29-20230127-35677-rbj5nt'
gmake: *** [Makefile:370: all] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!

  </pre>
</details>

## Output of `brew config`

<pre>
$ brew config
HOMEBREW_VERSION: 3.6.20
ORIGIN: https://github.com/Homebrew/brew
HEAD: 344d32bf7f40183359592ef81ca6486e0587981b
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2f0350ab74d4f44486460f04d32505beb50e0259
Core tap last commit: 19 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.39.1 => /opt/homebrew/bin/git
Curl: 7.84.0 => /usr/bin/curl
macOS: 13.0.1-arm64
CLT: 14.1.0.0.1.1666437224
Xcode: 14.2
Rosetta 2: false
</pre>

## Output of `brew doctor`

<pre>
$ brew doctor
Your system is ready to brew.
</pre>

**Comment by d12frosted** [comment] 2023-01-27 11:51
Try to retry 🙃

**Comment by Cliffzz** [comment] 2023-01-27 11:56
Hmm, just tried again. It did pull in some updates but same error basically.

<details>
  <summary>Command output</summary>
  <pre>
Already up-to-date.
➜  ~ brew doctor
Your system is ready to brew.
➜  ~ brew install emacs-plus@29
==> Fetching d12frosted/emacs-plus/emacs-plus@29
==> Cloning https://github.com/emacs-mirror/emacs.git
Updating /Users/cliffz/Library/Caches/Homebrew/emacs-plus@29--git
From https://github.com/emacs-mirror/emacs
   f72a394716..752c526585  emacs-29   -> origin/emacs-29
==> Checking out branch emacs-29
Already on 'emacs-29'
Your branch is behind 'origin/emacs-29' by 2 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
HEAD is now at 752c526585 ; Fix typos
==> Installing emacs-plus@29 from d12frosted/emacs-plus
==> Patching
==> Applying fix-window-role.patch
patching file 'src/nsterm.m'
==> Applying system-appearance.patch
patching file 'src/frame.h'
patching file 'src/nsfns.m'
patching file 'src/nsterm.m'
==> Applying round-undecorated-frame.patch
patching file 'src/frame.c'
patching file 'src/frame.h'
patching file 'src/nsfns.m'
patching file 'src/nsterm.h'
patching file 'src/nsterm.m'
==> ./autogen.sh
==> ./configure --enable-locallisppath=/opt/homebrew/share/emacs/site-lisp --infodir=/opt/homebrew/Cellar/emacs-plus@29/29.0.60/share/info/emacs --prefix=/opt/homebrew/Cellar/emacs-plus@29/29.0.60 --with-xml2 --with-gnutls --
==> gmake
Last 15 lines from /Users/cliffz/Library/Logs/Homebrew/emacs-plus@29/03.gmake:
gmake[2]: Leaving directory '/private/tmp/emacs-plusA29-20230127-86598-1s2bfy0/lisp'
gmake[1]: *** [Makefile:533: lisp] Error 2
gmake[1]: Leaving directory '/private/tmp/emacs-plusA29-20230127-86598-1s2bfy0'
gmake[1]: Entering directory '/private/tmp/emacs-plusA29-20230127-86598-1s2bfy0'
***
*** "make all" failed with exit status 2.
***
*** You could try to:
*** - run "make bootstrap", which might fix the problem
*** - run "make V=1", which displays the full commands invoked by make,
***   to further investigate the problem
***
gmake[1]: *** [Makefile:414: advice-on-failure] Error 2
gmake[1]: Leaving directory '/private/tmp/emacs-plusA29-20230127-86598-1s2bfy0'
gmake: *** [Makefile:370: all] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!

These open issues may also help:
Could not install emacs-plus@29 https://github.com/d12frosted/homebrew-emacs-plus/issues/544
  </pre>
</details>

**Comment by d12frosted** [comment] 2023-01-28 09:46
@Cliffzz I understand it's not helpful, but I can't reproduce in nor locally, nor on CI. As a wild guess, try cleaning `/Users/cliffz/Library/Caches/Homebrew/emacs-plus@29--git`. I know that sometimes it helps people.

**Comment by jvtrigueros** [comment] 2023-01-28 22:37
I just had the same issue, deleting the directory helped. Thank you!

**Comment by aport** [comment] 2023-01-29 04:00
I experienced this issue and deleting the cache repository did not help.
The error I saw was:
`In toplevel form:
cedet/semantic/wisent/python.el:30:2: Error: Symbol's function definition is void: treesit-parser-list
gmake[3]: *** [Makefile:332: cedet/semantic/wisent/python.elc] Error 1`

After installing `brew install tree-sitter` and rebuilding it was successful 👍🏻

**Comment by Cliffzz** [comment] 2023-01-29 13:19
@d12frosted No worries, I understand the inability to really do something witout a reproduction of the issue.

I tried deleting directory you mention but unfortunately that didn't rearlly do anything. After checking the gmake logs I had the same error as @aport. After installing tree-sitter manually it works.

**Comment by R0flcopt3r** [comment] 2023-02-01 10:32
@Cliffzz could you take look at the file `/Users/cliffz/Library/Logs/Homebrew/emacs-plus@29/03.gmake`? 

I have the same issues, and it's linking errors to ctags. Should this provide ctags by itself? or should i have to install it seperately? I had emacs installed, removed it along with all references to tags,ctags,etags. still having the same issue. Also tried to remove the cache.

Here is the relevant output from gmake:

```
# ...
Undefined symbols for architecture arm64:
  "_file_has_acl", referenced from:
      _connect_socket in emacsclient-2ec1ae.o
  "_rpl_faccessat", referenced from:
      _set_local_socket in emacsclient-2ec1ae.o
  "_rpl_free", referenced from:
      _get_current_dir_name in emacsclient-2ec1ae.o
      _main in emacsclient-2ec1ae.o
      _quote_argument in emacsclient-2ec1ae.o
      _set_tcp_socket in emacsclient-2ec1ae.o
  "_rpl_getopt_long_only", referenced from:
      _main in emacsclient-2ec1ae.o
  "_rpl_open", referenced from:
      _connect_socket in emacsclient-2ec1ae.o
      _local_sockname in emacsclient-2ec1ae.o
  "_rpl_optarg", referenced from:
      _main in emacsclient-2ec1ae.o
  "_rpl_optind", referenced from:
      _main in emacsclient-2ec1ae.o
      _fail in emacsclient-2ec1ae.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [Makefile:427: emacsclient] Error 1
gmake[2]: *** Waiting for unfinished jobs....
Undefined symbols for architecture arm64:
  "_rpl_free", referenced from:
      _globals in ebrowse-93ac4f.o
      _member in ebrowse-93ac4f.o
      _add_declarator in ebrowse-93ac4f.o
  "_rpl_getopt_long", referenced from:
      _main in ebrowse-93ac4f.o
  "_rpl_optarg", referenced from:
      _main in ebrowse-93ac4f.o
  "_rpl_optind", referenced from:
      _main in ebrowse-93ac4f.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [Makefile:411: ebrowse] Error 1
Undefined symbols for architecture arm64:
  "_c_isalnum", referenced from:
      _scan_c_stream in make-docfile-e09ce7.o
  "_rpl_free", referenced from:
      _main in make-docfile-e09ce7.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [Makefile:414: make-docfile] Error 1
Undefined symbols for architecture arm64:
  "_c_isalnum", referenced from:
      _Asm_labels in ctags-bcd890.o
      _Cobol_paragraphs in ctags-bcd890.o
      _Mercury_functions in ctags-bcd890.o
      _Perl_functions in ctags-bcd890.o
      _Prolog_functions in ctags-bcd890.o
      _Ruby_functions in ctags-bcd890.o
      _Ada_getit in ctags-bcd890.o
      ...
  "_c_strcasecmp", referenced from:
      _get_language_from_filename in ctags-bcd890.o
  "_c_strncasecmp", referenced from:
      _Forth_words in ctags-bcd890.o
      _Fortran_functions in ctags-bcd890.o
      _HTML_labels in ctags-bcd890.o
  "_rpl_free", referenced from:
      _main in ctags-bcd890.o
      _analyze_regex in ctags-bcd890.o
      _process_file_name in ctags-bcd890.o
      _free_regexps in ctags-bcd890.o
      _put_entries in ctags-bcd890.o
      _free_tree in ctags-bcd890.o
      _Erlang_functions in ctags-bcd890.o
      ...
  "_rpl_getopt_long", referenced from:
      _main in ctags-bcd890.o
  "_rpl_optarg", referenced from:
      _main in ctags-bcd890.o
  "_rpl_optind", referenced from:
      _main in ctags-bcd890.o
  "_rpl_re_compile_pattern", referenced from:
      _add_regex in ctags-bcd890.o
  "_rpl_re_match", referenced from:
      _readline in ctags-bcd890.o
  "_rpl_re_search", referenced from:
      _find_entries in ctags-bcd890.o
  "_rpl_re_set_syntax", referenced from:
      _add_regex in ctags-bcd890.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [Makefile:407: ctags] Error 1
Undefined symbols for architecture arm64:
  "_c_isalnum", referenced from:
      _Asm_labels in etags-657a8f.o
      _Cobol_paragraphs in etags-657a8f.o
      _Mercury_functions in etags-657a8f.o
      _Perl_functions in etags-657a8f.o
      _Prolog_functions in etags-657a8f.o
      _Ruby_functions in etags-657a8f.o
      _Ada_getit in etags-657a8f.o
      ...
  "_c_strcasecmp", referenced from:
      _get_language_from_filename in etags-657a8f.o
  "_c_strncasecmp", referenced from:
      _Forth_words in etags-657a8f.o
      _Fortran_functions in etags-657a8f.o
      _HTML_labels in etags-657a8f.o
  "_rpl_free", referenced from:
      _main in etags-657a8f.o
      _analyze_regex in etags-657a8f.o
      _process_file_name in etags-657a8f.o
      _free_regexps in etags-657a8f.o
      _put_entries in etags-657a8f.o
      _free_tree in etags-657a8f.o
      _Erlang_functions in etags-657a8f.o
      ...
  "_rpl_getopt_long", referenced from:
      _main in etags-657a8f.o
  "_rpl_optarg", referenced from:
      _main in etags-657a8f.o
  "_rpl_optind", referenced from:
      _main in etags-657a8f.o
  "_rpl_re_compile_pattern", referenced from:
      _add_regex in etags-657a8f.o
  "_rpl_re_match", referenced from:
      _readline in etags-657a8f.o
  "_rpl_re_search", referenced from:
      _find_entries in etags-657a8f.o
  "_rpl_re_set_syntax", referenced from:
      _add_regex in etags-657a8f.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [Makefile:400: etags] Error 1
gmake[2]: Leaving directory '/private/tmp/emacs-plusA29-20230201-31543-1qcbi19/lib-src'
gmake[1]: *** [Makefile:533: lib-src] Error 2
gmake[1]: *** Waiting for unfinished jobs....```

**Comment by Ethanlinyf** [comment] 2023-02-14 05:21
not about to install @29

`==> gmake
Last 15 lines from /Users/ethanlin/Library/Logs/Homebrew/emacs-plus@29/03.gmake:
gmake[2]: Leaving directory '/private/tmp/emacs-plusA29-20230214-2769-r1jxyu/lisp'
gmake[1]: *** [Makefile:533: lisp] Error 2
gmake[1]: Leaving directory '/private/tmp/emacs-plusA29-20230214-2769-r1jxyu'
gmake[1]: Entering directory '/private/tmp/emacs-plusA29-20230214-2769-r1jxyu'
***
*** "make all" failed with exit status 2.
***
*** You could try to:
*** - run "make bootstrap", which might fix the problem
*** - run "make V=1", which displays the full commands invoked by make,
***   to further investigate the problem
***
gmake[1]: *** [Makefile:414: advice-on-failure] Error 2
gmake[1]: Leaving directory '/private/tmp/emacs-plusA29-20230214-2769-r1jxyu'
gmake: *** [Makefile:370: all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/d12frosted/homebrew-emacs-plus/issues

These open issues may also help:
Could not install emacs-plus@29 https://github.com/d12frosted/homebrew-emacs-plus/issues/544`

**Comment by tzz** [comment] 2023-02-19 05:58
I have a problem building `@29`. I tried with no extra options as well, same error. `@30` has the same error as well. This is on a M1. `@28` works.

```
❯ cat ~/Library/Logs/Homebrew/emacs-plus@29/00.options.out
d12frosted/emacs-plus/emacs-plus@29 --with-imagemagick --with-native-comp --with-no-frame-refocus
```

And then in `~/Library/Logs/Homebrew/emacs-plus@29/03.gmake`

```
Dumping under the name bootstrap-emacs.pdmp
Dumping fingerprint: d4dc2c48fa9f82abbf5ffcaa17058f8dfa1a4edeccb5ba3ba63879aa362cba7f
Dump complete
Byte counts: header=100 hot=13652772 discardable=195472 cold=6890440
Reloc counts: hot=796163 discardable=5352
```

but just a little later in the build process (the error repeats with the same fingerprint mismatch):

```
'../src/emacs' -batch --no-site-file --no-site-lisp --eval "(setq load-prefer-newer t byte-compile-warnings 'all)"  \
-l comp -f batch-byte+native-compile org/ox.el
desired fingerprint: d4dc2c48fa9f82abbf5ffcaa17058f8dfa1a4edeccb5ba3ba63879aa362cba7f
found fingerprint: dd0a836822fb1c9fa3987e59d656133b927ff0575ec9b0b4ca5b1658f987634f
emacs: could not load dump file "/private/tmp/emacs-plusA29-20230218-33549-301jtr/src/emacs.pdmp": not built for this Emacs executable
```

`brew doctor` had nothing relevant.

```
❯ brew config
HOMEBREW_VERSION: 4.0.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 17c872fb5275d87922a56416587cb439a5064354
Last commit: 3 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0f87d15ad2a094b10d662ecdaea3c944272804ff
Core tap last commit: 25 hours ago
Core tap branch: master
Core tap JSON: 19 Feb 05:41 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.39.0 => /opt/homebrew/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
Rosetta 2: false
```

**Comment by dmgerman** [comment] 2023-03-23 05:34
> not able to install @29

I had the same error. I was able to install by removing first the directory ~/Library/Caches/Homebrew

**Comment by belak** [comment] 2023-08-08 16:21
As far as I can tell, this is an issue with something in the PATH, somehow.

I ran `PATH=/opt/homebrew/bin:/usr/bin:/bin brew install emacs-plus@29 --with-native-comp` and it worked fine, though because this formula injects the PATH variable, the final injected path isn't going to have everything I need so I plan to investigate a bit more.

**Comment by belak** [comment] 2023-08-08 16:34
I have it narrowed down to this PATH directory which contains the following:
```
/Users/belak/.nix-profile/bin:
2to3           dig                         git-receive-pack    idle3              objcopy                  python3-config       stress
2to3-3.11      digraph                     git-rustfmt         idle3.11           objdump                  python3.11           stringer
7z             direnv                      git-shell           ifaceassert        pipes-rs                 python3.11-config    stringintconv
7za            dos2unix                    git-upload-archive  install_name_tool  pkg-config               ranlib               strings
7zr            editorconfig                git-upload-pack     jq                 present                  rbenv                strip
accessdb       editorconfig-0.12.5         gitauth             killall            present2md               rbenv-install        svgo
addr2line      eg                          gitui               lexgrog            protoc                   rbenv-uninstall      tmux
apropos        elfedit                     go                  lftp               protoc-3.21.12.0         readelf              toolstash
ar             ex                          go-contrib-init     lftpget            protoc-gen-go            rg                   unix2dos
authtest       fd                          godex               lostcancel         protoc-gen-go-grpc       rnix-lsp             unix2mac
bat            fieldalignment              godoc               mac2unix           pwgen                    ruby-build           unmarshal
benchcmp       file2fuzz                   gofmt               man                pydoc                    rust-analyzer        unzip
bundle         find                        gofumpt             man-recode         pydoc3                   rust-gdb             unzipsfx
c++filt        findcall                    goimports           mandb              pydoc3.11                rust-gdbgui          vi
callgraph      fiximports                  golangci-lint       manpath            pyenv                    rust-lldb            view
cargo          funzip                      gomvpkg             mbsync             pyenv-activate           rustc                vim
cargo-clippy   fuzz-driver                 gopackages          mbsync-get-cert    pyenv-deactivate         rustdoc              vimdiff
cargo-fmt      fuzz-runner                 goreleaser          mdconvert          pyenv-sh-activate        rustfmt              vimtutor
catman         fzf                         gorename            mu                 pyenv-sh-deactivate      rustfmt-format-diff  virtualenv
clippy-driver  fzf-share                   gostacks            netrcauth          pyenv-virtualenv         rview                wget
cloc           fzf-tmux                    gotype              nilness            pyenv-virtualenv-delete  rvim                 whatis
cmatrix        git                         goyacc              nm                 pyenv-virtualenv-init    scalar               xargs
compilebench   git-credential-netrc        guru                nslookup           pyenv-virtualenv-prefix  sdl-config           xxd
cookieauth     git-credential-osxkeychain  home-manager        nsupdate           pyenv-virtualenvs        shadow               yarn
crane          git-cvsserver               html2article        nvim               python                   size                 yarnpkg
curl           git-http-backend            htop                nvim-python3       python-config            splitdwarf           zipgrep
delv           git-jump                    idle                nvim-ruby          python3                  ssadump              zipinfo
```

**Comment by roife** [comment] 2023-10-07 15:48
Uninstalling `binutils` indeed solves the problem, thanks to @belak!

**Comment by maruks** [comment] 2024-06-18 18:16
I get this error:
```

% brew install emacs-plus@29
==> Fetching d12frosted/emacs-plus/emacs-plus@29
==> Downloading https://ftp.gnu.org/gnu/emacs/emacs-29.3.tar.xz
Already downloaded: /Users/maris/Library/Caches/Homebrew/downloads/36b84a67854d2e937bc9f499d87c82814f8e46ce3912cb8b1a448ea23ea50fb5--emacs-29.3.tar.xz
==> Installing emacs-plus@29 from d12frosted/emacs-plus
==> Patching
cp: invalid option -- 'c'
Try 'cp --help' for more information.
```


HOMEBREW_VERSION: 4.3.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: e8430b25a1d1321f32e5093d62b57b5cb7cfb3c3
Last commit: 2 days ago
Core tap JSON: 18 Jun 18:10 UTC
Core cask tap JSON: 18 Jun 18:10 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 3.3.3 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/bin/ruby
CPU: dodeca-core 64-bit arm_lobos
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.4-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
Rosetta 2: false

**Comment by mdempsky** [comment] 2024-06-22 04:41
I'm also getting the "cp: invalid option -- 'c'" error. I hacked around the issue by temporarily replacing `/opt/homebrew/Cellar/coreutils/9.5/libexec/gnubin/cp` with a symlink to `/bin/cp`, and then restoring the original after `brew install emacs-plus` finished.

```
% brew config
HOMEBREW_VERSION: 4.3.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: e8430b25a1d1321f32e5093d62b57b5cb7cfb3c3
Last commit: 6 days ago
Core tap JSON: 22 Jun 04:33 UTC
Core cask tap JSON: 22 Jun 04:33 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.3.3 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/bin/ruby
CPU: octa-core 64-bit arm_ibiza
Clang: 16.0.0 build 1600
Git: 2.39.4 => /Applications/Xcode-beta.app/Contents/Developer/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.0-arm64
CLT: 16.0.0.0.1.1717710328
Xcode: 16.0 => /Applications/Xcode-beta.app/Contents/Developer
Rosetta 2: false
```

**Comment by d12frosted** [comment] 2024-06-28 05:57
The issue with cp should be fixed in the latest release of homebrew. Update it and try again.

https://github.com/d12frosted/homebrew-emacs-plus/issues/688#issuecomment-2186413911

Closing the issue as original is unrelated to currently discussed issues; the original one doesn't seem to manifest anymore; and the new one is already fixed.

**Closed by d12frosted** 2024-06-28 05:57 UTC
Labels: install error
