### ISSUE TITLE
Could not install emacs-plus@30 with --with-xwidgets --with-imagemagick --with-native-comp --with-poll --with-compress-install --with-memeplex-wide-icon

### ISSUE THREAD

**Issue by cxb811201** [d12frosted/homebrew-emacs-plus#608] opened 2023-09-04 09:59 UTC
Please make sure to follow these steps (and mark the checkboxes):

- [x] run `brew update` and try to reproduce the issue again
- [x] run `brew doctor`, fix all issues and try to reproduce your issue again
- [x] run `brew config` and `brew doctor` and include their output

## What you were trying to do

I was trying to (re-)install emacs-plus@30 on a MacBook Pro M2.

## What happened (include command output)

<pre>
$ brew install emacs-plus --with-xwidgets --with-imagemagick --with-native-comp --with-poll --with-compress-install --with-memeplex-wide-icon
</pre>

<details>
  <summary>Command output</summary>
  <pre>

  Error: can't modify frozen class

  </pre>
</details>

## Problem
https://github.com/Homebrew/brew/commit/e7d0625776dca58c81b03c19eeda1af8bd6bb58e  caused the above problem.

## Solution
After switching homebrew to https://github.com/Homebrew/brew/commit/9b76182c119abca16eaa3b1faa64bd08ca112be3, re-executing the install command solves the above problem.

## Output of `brew config`

<pre>
$ brew config
HOMEBREW_VERSION: 4.1.7-59-gb535088
ORIGIN: https://github.com/Homebrew/brew
HEAD: b53508897b9e761948da9585b3ca55cf9d2abeb3
Last commit: 14 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 838a2aa8e68159910c6a3d6d519bc126f1cb03e8
Core tap last commit: 62 minutes ago
Core tap branch: master
Core tap JSON: 04 Sep 09:49 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_API_DOMAIN: https://mirrors.ustc.edu.cn/homebrew-bottles/api
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.ustc.edu.cn/homebrew-bottles
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 12
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 14.0.3 build 1403
Git: 2.42.0 => /opt/homebrew/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5.1-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: 14.3.1
Rosetta 2: false
</pre>

## Output of `brew doctor`

<pre>
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause GMP builds to fail.

Warning: Putting non-prefixed findutils in your path can cause python builds to fail.

Warning: A '.pydistutils.cfg' file was found in $HOME, which may cause Python
builds to fail. See:
  https://bugs.python.org/issue6138
  https://bugs.python.org/issue4655
</pre>

**Comment by cxb811201** [comment] 2023-09-04 10:12
The above error occurs with the latest homebrew.
The above error occurs with the latest homebrew.
If you use [ec9bb2fe6848bc9e2336843682b21385e58fd827](https://github.com/Homebrew/brew/commit/ec9bb2fe6848bc9e2336843682b21385e58fd827), the installation proceeds normally.

**Comment by cxb811201** [comment] 2023-09-04 10:20
After checking, it should be the https://github.com/Homebrew/brew/commit/e7d0625776dca58c81b03c19eeda1af8bd6bb58e commit that is causing the problem.

**Comment by d12frosted** [comment] 2023-09-04 11:24
Closing as duplicate of https://github.com/d12frosted/homebrew-emacs-plus/issues/602.

**Closed by d12frosted** 2023-09-04 11:24 UTC
Labels: install error

**Comment by d12frosted** [comment] 2023-09-04 11:26
Although this one nicely summarises the issue.

**Comment by d12frosted** [comment] 2023-09-04 18:01
Thanks to @juliocc , this should be fixed by now. Please do an update and try installing Emacs+ again.
