### ISSUE TITLE
[Feature request]: Support :stipple face attribute

### ISSUE THREAD

**Issue by sentorxx** [d12frosted/homebrew-emacs-plus#732] opened 2024-09-22 07:43 UTC
### Feature request description

Hi,

thanks for this project. Is it possible to support the :stipple face attribute to use [indent-bars](https://github.com/jdtsmith/indent-bars) in your build?

Here is a [patch](https://bitbucket.org/mituharu/emacs-mac/commits/25d1a744fc68eb8cd4e37443ac8ac3f7465f128e/raw) which was used in the [emcs-mac](https://github.com/railwaycat/homebrew-emacsmacport) port. 

Some further [infos](https://www.reddit.com/r/emacs/comments/15d377q/comment/ju26uqc/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button).

Thanks for thinking about this :)

**Comment by d12frosted** [comment] 2024-09-22 08:05
Hey. It's a duplicate of #622.

In short, that commit doesn't apply cleanly and depends on many modifications to emacs-mac port. It's best to request this from upstream.

**Closed by d12frosted** 2024-09-22 08:05 UTC
Labels: feature request

**Comment by sentorxx** [comment] 2024-09-22 08:12
Thanks for quick answer and your great project.

Greetings :)
