### ISSUE TITLE
Question about @29's (add-to-list 'default-frame-alist '(undecorated . t))

### ISSUE THREAD

**Issue by frankjonen** [d12frosted/homebrew-emacs-plus#584] opened 2023-05-11 17:15 UTC
When I put that in I get a tiny centred window that is, well… undecorated.

It seems to collide with this one:

```elisp
(add-to-list 'initial-frame-alist '(fullscreen . maximized))
```

Doesn't matter if I put `(add-to-list 'default-frame-alist '(undecorated . t))` above or below it. I launch Emacs with that in, it goes `bop sound` and stays tiny.

Anyone had the same issue?

**Comment by d12frosted** [comment] 2023-05-11 18:41
I just disabled `yabai` to reproduce it on Emacs v30. Added these lines to the my `early-init.el` and removed all `elc` files (so they don't collide):

```emacs-lisp
(add-to-list 'initial-frame-alist '(fullscreen . maximized))
(add-to-list 'default-frame-alist '(undecorated . t))
```

When I start Emacs I get a maximized frame without any decorations. My guess:

1. Make sure you have these in `early-init`.
2. Make sure that you don't have any `elc` files in your config directory.
3. Optionally try Emacs 30. Will be able to test with Emacs 29 tomorrow.
4. If you are using any window managers (yabai, ametist, etc.) - disable them for testing purposes.

**Comment by frankjonen** [comment] 2023-05-11 23:17
I put it in my config instead of my init, that was the issue. I got it to work now and it's atrocious now compared to how it worked before. With these settings Emacs launches with a nasty white full-screen flash.

It's not worth it, really hurts my eyes when the entire screen flashes white (might need an epilepsy warning). I'm sticking with windowed mode until a non-flashing option like in @27 becomes available.

**Comment by d12frosted** [comment] 2023-05-12 04:35
> I put it in my config instead of my init, that was the issue. I got it to work now

I see. Well, `default-frame-alist` and `initial-frame-alist` should be modified as soon as possible to be applied to the first frame. So that's why it's considered a good idea to put them specifically in the `early-init.el` file. 

> and it's atrocious now compared to how it worked before. With these settings Emacs launches with a nasty white full-screen flash.

Not sure I understand. Can you please test these options without any other configurations?

For example, you can put the following lines in some `el` file and start Emacs only with loading this file.

(1) Create some `early-init.el` in any location.

```emacs-lisp
(add-to-list 'default-frame-alist '(fullscreen . maximized))
(add-to-list 'default-frame-alist '(undecorated . t))
```

(2) Start Emacs from terminal without loading your configurations, but only the specified file.

```bash
$ emacs -Q --load ~/.config/emacs/early-init.el
```

---

I am currently on Emacs 30. And this is how it looks. Don't see any flashing.

https://github.com/d12frosted/homebrew-emacs-plus/assets/6507913/9ce23f2d-9296-4e3b-ab10-a70078150ae5

As you can see in the recording I commented most of the options in my `early-init.el` file. And also I have enabled yabai (tiling window manager) to make sure that fullscreen option is properly used.

**Comment by frankjonen** [comment] 2023-05-12 16:51
Just did that with @29. Only brings up a white empty frame. Maybe it flashed earlier because I only modified the `doom.d` init instead of the `early-init` in the emacs folder. White on white flashing is pretty impossible to detect though.

My setup is now really screwed up as a result of having @29 and @27 on the same system. Wasn't a good idea to keep a productive system along with a test system.

I'm back on @27 anyway because neither @28 nor @29 work right. 28 crashes on session save exit and 29 can't restore auto-saved sessions.

**Comment by remi-gelinas** [comment] 2023-05-13 21:21
@d12frosted Odd - on MacOS 13.3, `aarch64-darwin`, with Emacs 30 and yabai disabled I get the same result as you except yabai refuses to tile the window. If I load my normal configuration (with those two options being placed in my `early-init`, I get the ugly fullscreen white flash, but then my configured Emacs that yabai CAN tile - super weird

**Comment by remi-gelinas** [comment] 2023-05-13 21:26
@d12frosted Recorded a minimal reproduction: 

https://github.com/d12frosted/homebrew-emacs-plus/assets/3160654/88bc7000-be36-42aa-8515-fe63646a0c25

**Comment by remi-gelinas** [comment] 2023-05-13 21:35
Sorry, I realized opening it from the CLI only resulted in the emacs window flashing white - here is opening the MacOS app bundle:

https://github.com/d12frosted/homebrew-emacs-plus/assets/3160654/be285d23-d88f-4947-b7e0-65437fdd1b4f

**Comment by frankjonen** [comment] 2023-05-14 01:08
Thanks for confirming @remi-gelinas. I'm on 12.6.5 Intel btw and launch from the app bundle.

**Comment by d12frosted** [comment] 2023-05-14 06:21
@remi-gelinas I think now I understand what's causing the 'flashing'. The theme is applied with delay :) I am using white theme, so I didn't notice it.

At the moment, I am not sure how to help you. Since it's not related to Emacs+ specifically, but rather to Emacs in general, I guess you will have more luck asking in mailing lists/reddit. Sorry :(

**Comment by remi-gelinas** [comment] 2023-05-14 09:59
@d12frosted That's fair! I'll take that issue elsewhere. As for the command line run Emacs not tiling, would you rather I open a separate issue for that? Or is that just a caveat caveat to running on Mac?

**Comment by g6ai** [comment] 2024-01-10 14:03
@remi-gelinas I wonder have you opened a separate issue for this? I'm interested in following it

**Comment by d12frosted** [comment] 2024-01-11 07:02
If the tiling issue still persists, let me know. 

I am closing this issue as it's out of Emacs+ scope.

**Closed by d12frosted** 2024-01-11 07:02 UTC
