### ISSUE TITLE
emacs doesn't take up the entire screen

### ISSUE THREAD

**Issue by michaelssingh** [d12frosted/homebrew-emacs-plus#619] opened 2023-09-27 19:33 UTC
<img width="1278" alt="image" src="https://github.com/d12frosted/homebrew-emacs-plus/assets/61710484/e1f7d86e-f918-42bc-8b1a-1c3f3df2e2cb">

I'm interested in understanding if this is expected

**Comment by michaelssingh** [comment] 2023-09-27 19:33
Notice the space at the bottom of emacs?

**Comment by d12frosted** [comment] 2023-09-28 07:40
How do you setup full screen? Is it achieved my Emacs configuration or by some window manager?

**Comment by d12frosted** [comment] 2023-09-28 07:41
Ah, and which Emacs are you running?

**Comment by michaelssingh** [comment] 2023-09-28 13:52
This is emacs 29. I use a WM, but recently, I tried Doom emacs, which magically solved the issue.  I am very new to Emacs, by the way.

**Comment by d12frosted** [comment] 2023-10-03 04:34
I am asking because there are multiple ways to achieve it. For example, I don't control how much space Emacs occupies on my screen through Emacs Lisp as IMO it's responsibility of my window manager. But Emacs has options for that (you can control initial frame options). And AFAIK some might not properly calculate the height due to pixel-wise/non-pixel-wise variations and the timing of some other things happening due init. Although I don't remember details.

Glad to hear that Doom Emacs solved the issue for you.

It seems that the issue is not related to Emacs+ (e.g. formula for brew), so closing it. But I encourage everyone to continue discussion here.

**Closed by d12frosted** 2023-10-03 04:34 UTC
Labels: question
