### ISSUE TITLE
warning - libgccjit.so: error: error invoking gcc driver

### ISSUE THREAD

**Issue by anildigital** [d12frosted/homebrew-emacs-plus#323] opened 2021-03-23 05:56 UTC
## What you were trying to do

I have installed Emacs on macOS Big Sur using following command

`brew install emacs-plus@28 --with-native-comp`

## What happened (include command output)

<pre>
$ brew install emacs-plus [OPTIONS]
</pre>

<details>
  <summary>Command output</summary>
  <pre>
Warning (comp): libgccjit.so: error: error invoking gcc driver Disable showing Disable logging
Warning (comp): /usr/local/Cellar/emacs-plus@28/28.0.50/share/emacs/28.0.50/lisp/emacs-lisp/cl-lib.el.gz: Error: Internal native compiler error failed to compile Disable showing Disable logging
  </pre>
</details>

## Output of `brew config`

<pre>
$ brew config
HOMEBREW_VERSION: 3.0.8-32-g9a355b0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9a355b07c3706d9c0477827009ae817c8749261d
Last commit: 21 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5f905845a19ef0d32641a3e0db131cd5a991b1ff
Core tap last commit: 34 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: 192.168.59.3:0
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.31.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.3-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4

</pre>

## Output of `brew doctor`

<pre>
$ brew doctor

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  guile@2

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libwkhtmltox.0.12.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/wkhtmltox/image.h
  /usr/local/include/wkhtmltox/pdf.h

Warning: You have uncommitted modifications to Homebrew/homebrew-core.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core && git stash && git clean -d -f

Uncommitted files:
   M Formula/wxmac.rb
</pre>

**Comment by d12frosted** [comment] 2021-03-23 06:41
Hard to tell what's wrong. I would love to hear all the steps you did prior to getting this error (including any modifications to `LD_LIBRARY_PATH`, `LIBRARY_PATH` or alike).

You may try [this][1] and [this][2].

[1]: https://github.com/d12frosted/homebrew-emacs-plus/issues/309#issuecomment-778799638
[2]: https://github.com/d12frosted/homebrew-emacs-plus/issues/187#issuecomment-749842134

**Comment by anildigital** [comment] 2021-03-23 07:58
@d12frosted So I tried this from terminal

```bash
env LIBRARY_PATH="/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib"
...
...
LIBRARY_PATH=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib
anil@mbp ~> /Applications/Emacs.app/Contents/MacOS/Emacs
```

and it now shows only this warning

```
Warning (comp): seq.el.gz:396:16: Warning: ‘seq-contains’ is an obsolete generic function (as of 27.1); use ‘seq-contains-p’ instead. Disable showing Disable logging
```

But putting following at the top of `init.el` or even `early-init.el` doesn't help

```
(setenv "LIBRARY_PATH" "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib")
```

I am not sure how to fix this now

**Comment by d12frosted** [comment] 2021-03-23 08:20
That's because when you start applications from finder (or spotlight), environment is very different. There are many ways of dealing with this (one of the viable solutions is to use [exec-path-from-shell][1]). But in this particular case I would [avoid messing][2] with `LIBRARY_PATH` and rather reinstall `libgccjit` and try again (afaik, no need to build from sources):

```bash
$ brew uninstall libgccjit
$ brew install libgccjit
```

Hope that helps.

[1]: https://github.com/purcell/exec-path-from-shell
[2]: https://github.com/d12frosted/homebrew-emacs-plus/pull/302

**Comment by anildigital** [comment] 2021-03-23 11:08
@d12frosted I did try above uninstall, install for gcc and libgccjit. But it seems not helping. Still getting following warnings when I start Emacs from Spotlight/Finder.

```
Warning (comp): libgccjit.so: error: error invoking gcc driver Disable showing Disable logging
Warning (comp): /usr/local/Cellar/emacs-plus@28/28.0.50/share/emacs/28.0.50/lisp/emacs-lisp/cl-lib.el.gz: Error: Internal native compiler error failed to compile Disable showing Disable logging

```

Also I do use `exec-path-from-shell`, but that seems not helping either.

**Comment by anildigital** [comment] 2021-03-23 12:41
@d12frosted Emacs is working fine irrespective of above warnings. Does that mean I can ignore these warnings and there is no impact in performance of Emacs?

**Comment by d12frosted** [comment] 2021-03-23 13:12
> Also I do use exec-path-from-shell, but that seems not helping either.

I believe that in the case of gccemacs, `exec-path-from-shell` happens too late.

> Does that mean I can ignore these warnings and there is no impact in performance of Emacs?

AFAIU, it means that gccemacs is not working for you :) And you will run into these warnings quite often and you will not get any performance gain. 

Can you please share output of your `env`? :) But before blindly sharing it, please make sure to remove any lines containing any sensitive information. I am mostly interested in various gcc-related values.

**Comment by anildigital** [comment] 2021-03-24 04:46
Putting following in early-init.el fixed the issue
```
(setenv "LIBRARY_PATH" "/usr/local/opt/gcc/lib/gcc/10:/usr/local/opt/libgccjit/lib/gcc/10:/usr/local/opt/gcc/lib/gcc/10/gcc/x86_64-apple-darwin20/10.2.0")
```

Please note, I have installed gcc and libgccjit *without* flag ```--force --build-from-source``` with homebrew. I didn't try building from source as it was taking a lot of time (More than 20 mins)

I still see this warning though

```
Warning (comp): seq.el.gz:396:16: Warning: ‘seq-contains’ is an obsolete generic function (as of 27.1); use ‘seq-contains-p’ instead. Disable showing Disable logging
```

Is there any function or way which tells that gccemacs is perfectly working fine? As Emacs seems working fine from usability perspective.

**Comment by d12frosted** [comment] 2021-03-24 07:12
Well, modifying `LIBRARY_PATH` is a workaround, dirty one, not future-proof, but still a workaround. Not sure what's wrong with your env though and why it doesn't work for you. I will clean install soon to see the process from the beginning (I've been medling with my env so much during my attempts to introduce `--with-native-comp` option) 😸 

AFAIK, there is no tool to check this. If it works, it works 😸 Those warnings are totally fine to see.

**Comment by jimeh** [comment] 2021-03-24 17:22
@anildigital You can use `M-x describe-function [RET] <func-name>` to see if a specific function is natively compiled or not. For example doing so with `ibuffer` should yield this:

```
ibuffer is an interactive native compiled Lisp function in
‘ibuffer.el’.
```

However, if it's a auto-loaded function that hasn't been loaded yet, it will not mention native comp, for example, this is the output for `M-x describe-function [RET] tramp-version` for me before tramp is loaded:

```
tramp-version is an autoloaded interactive compiled Lisp function in
‘tramp-cmds.el’.
```

And this is after tramp is loaded:

```
tramp-version is an interactive native compiled Lisp function in
‘tramp-cmds.el’.
```

**Comment by anildigital** [comment] 2021-03-25 12:28
@jimeh I see following

```
ibuffer is an autoloaded interactive compiled Lisp function in
‘ibuffer.el’.

(ibuffer &optional OTHER-WINDOW-P NAME QUALIFIERS NOSELECT SHRINK
FILTER-GROUPS FORMATS)

  Probably introduced at or before Emacs version 22.1.

Begin using Ibuffer to edit a list of buffers.
Type C-h m after entering ibuffer for more information.
```

**Comment by jimeh** [comment] 2021-03-25 12:39
@anildigital Try `ibuffer` again after opening it with `M-x ibuffer`, cause it looks like ibuffer has not been loaded.

As for magit, it looks like it has been loaded, but not been native compiled. This would suggest either something is wrong with native compilation for externally installed packages, or it's just not working in general. If ibuffer is native compiled after using it, it's related to external packages.

Do you have a `*Async-native-compile-log*` buffer? It should hopefully give some hints as to whats going on.

**Comment by anildigital** [comment] 2021-03-25 13:47
@jimeh Yep it shows now for `ibuffer`

```
ibuffer is an interactive native compiled Lisp function in
‘ibuffer.el’.
```

for magit

I now see
```
magit-log is an interactive native compiled Lisp function in
‘magit-log.el’.
...
magit-mode is an interactive native compiled Lisp function in
‘magit-mode.el’.
...
magit-status is an interactive native compiled Lisp function in
‘magit-status.el’.
...
magit-diff is an interactive native compiled Lisp function in
‘magit-diff.el’.
```

I wonder why it was not showing native compiled before. `*Async-native-compile-log*` seems fine and shows compiling various packages.

**Comment by jimeh** [comment] 2021-03-25 14:13
@anildigital in that case everything should be fine. I imagine it wasn't showing before you hadn't run `magit-status` since you launched Emacs. If you had, then ¯\\\_(ツ)_/¯

**Comment by d12frosted** [comment] 2021-03-27 07:52
Thanks @jimeh for your help!

Closing the issue as it seems that everything is working now.

**Closed by d12frosted** 2021-03-27 07:52 UTC
Labels: install error

**Comment by ccann** [comment] 2021-06-04 23:43
I just had this issue as well and following [this suggestion](https://github.com/d12frosted/homebrew-emacs-plus/issues/309#issuecomment-778799638) you linked earlier in the thread @d12frosted to get it working, though I have no idea why that worked.

**Comment by johangrahn** [comment] 2022-04-28 11:04
I use the same suggestion as ☝🏽 and it worked for me as well.

**Comment by queitsch** [comment] 2022-05-29 19:59
Thanks for the pointer, @anildigital !

If users of the Mitsuharu Yamamoto / railwaycat homebrew build stumble over this (like I did), these paths in `~/.emacs.d/early-init.el` worked for me:

```
(setenv "LIBRARY_PATH" "/opt/homebrew/opt/gcc/lib/gcc/11:/opt/homebrew/opt/libgccjit/lib/gcc/11:/opt/homebrew/opt/gcc/lib/gcc/11/gc\
c/aarch64-apple-darwin21/11")
```

**Comment by queitsch** [comment] 2022-09-07 11:27
And sure enough the workaround broke with gcc going to version 12, new line:
```
(setenv "LIBRARY_PATH" "/opt/homebrew/opt/gcc/lib/gcc/12:/opt/homebrew/opt/libgccjit/lib/gcc/12:/opt/homebrew/opt/gcc/lib/gcc/12/gcc/aarch64-apple-darwin21/12")
```

**Comment by lamtt77** [comment] 2022-10-28 04:23
I had encountered the same issue and fixed by the following steps (not needed setenv):
1) sudo rm -rf /Library/Developer/CommandLineTools
2) Manually download and install latest Xcode CommandLineTools from https://developer.apple.com/download/all/
3) sudo xcode-select -s /Library/Developer/CommandLineTools
4) Optional (I think): brew uninstall and install emacs-plus

**Comment by visigoth** [comment] 2023-01-13 17:13
for anyone else running into this, i also fixed this by simply running `xcode-select --install`.

**Comment by archit-rastogi** [comment] 2023-01-13 19:09
Worked for me on MacOs Sur with below entry in early-init.el as metioned above:
```
(setenv "LIBRARY_PATH" "/usr/local/Cellar/gcc/12.2.0:/usr/local/Cellar/libgccjit/12.2.0/lib/gcc/current:\
/usr/local/Cellar/gcc/12.2.0/lib/gcc/current/gcc/x86_64-apple-darwin20/12")
```

**Comment by gcentauri** [comment] 2023-10-11 21:50
FWIW I had this issue when trying to write a launcher for Emacs, and just adding the line brew adds to `.zprofile` to my startup script seemed to fix it

`eval "$(/usr/local/bin/brew shellenv)"`

its likely that the macos launcher is somehow missing this brew environment, it seems better to me to change the environment where emacs is launched from rather than to set it within emacs via lisp

**Comment by d12frosted** [comment] 2023-10-12 05:27
@gcentauri apps you launch from finder/launchctl/etc do use their own environment (login shell env). I tried to explain it a bit in [the announcement of PATH injection for Emacs+](https://d12frosted.io/posts/2022-05-12-emacs-plus-path-injection.html). There I talk about PATH variable, but it's applicable to anything you have in your interactive shell and not in system login shell.

**Comment by YHN-ice** [comment] 2024-02-20 18:21
I also encountered this error when I tried to use package [copilot.el](https://github.com/copilot-emacs/copilot.el.git) and invoked a native-compiled function. When I tried to rebuild gccemacs to fix it I got another [error](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjLuIi-wrqEAxXsrokEHSVXBSYQFnoECBgQAQ&url=https%3A%2F%2Fforums.developer.apple.com%2Fforums%2Fthread%2F722490&usg=AOvVaw1FkT0XC8sCJ7xYTrLZZWz9&opi=89978449) of 

``` 
ld: unsupported tapi file type '!tapi-tbd' in YAML file
```

In my case it was caused by [this problem (and solution)](https://stackoverflow.com/questions/74318052/cant-compile-fortran-on-macos-monterey-ld-unsupported-tapi-file-type-tapi-t) from `ld` of anaconda. I am using macOS 12.7.1 Monterey. I just removed conda bin directory from my `$PATH`, since I rarely use `conda env`.

**Comment by hazardfn** [comment] 2025-02-14 14:13
`SPC f e C-e` fixed this for me.

**Comment by queitsch** [comment] 2025-03-25 08:32
> And sure enough the workaround broke with gcc going to version 12, new line:
> 
> ```
> (setenv "LIBRARY_PATH" "/opt/homebrew/opt/gcc/lib/gcc/12:/opt/homebrew/opt/libgccjit/lib/gcc/12:/opt/homebrew/opt/gcc/lib/gcc/12/gcc/aarch64-apple-darwin21/12")
> ```

Hi! It's 2025, this bit me again. In the meantime I even switched from the Mitsuharu Yamamoto / railwaycat build to emacs-plus 30.1!

The line in `~/.emacs.d/early-init.el` is now:

``` emacs-lisp
(setenv "LIBRARY_PATH" "/opt/homebrew/opt/gcc/lib/gcc/current:/opt/homebrew/opt/libgccjit/lib/gcc/current:/opt/homebrew/opt/gcc/lib/gcc/current/gcc/aarch64-apple-darwin24/14")
```

It'll be different on Intel Macs / non-homebrew `gcc`.

The dock icon hops for quite a while as it's compiling all your packages before opening the first frame, start from the command line with `-nw` if you want to see what's going on.

I haven't tried moving the line `early-init.el` to `init.el` and have utterly forgotten why I put it there in the first place.

**Comment by d12frosted** [comment] 2025-03-28 08:25
> I haven't tried moving the line early-init.el to init.el and have utterly forgotten why I put it there in the first place.

Because you need to tell the location of GCC JIT *before* anything compiles 😅 Hence the early init, which is loaded during Emacs startup (unlike normal init file). A bit of info can be found [here](https://www.gnu.org/software/emacs/manual/html_node/emacs/Early-Init-File.html).

**Comment by jimeh** [comment] 2025-03-28 19:10
@queitsch If you want something future-proof that dynamically finds the relevant GCC paths from Homebrew on macOS, so GCC upgrades and such are just picked up automatically, try replacing your `setenv` call in `early-init.el` with this snippet:

```elisp
(defun homebrew-gcc-paths ()
  "Return GCC library paths from Homebrew installations.
Detects paths for gcc and libgccjit packages to be used in LIBRARY_PATH."
  (let* ((paths '())
         (brew-bin (or (executable-find "brew")
                       (let ((arm-path "/opt/homebrew/bin/brew")
                             (intel-path "/usr/local/bin/brew"))
                         (cond
                          ((file-exists-p arm-path) arm-path)
                          ((file-exists-p intel-path) intel-path))))))

    (when brew-bin
      ;; Get gcc paths.
      (let* ((gcc-prefix (string-trim
                         (shell-command-to-string
                          (concat brew-bin " --prefix gcc"))))
             (gcc-lib-current (expand-file-name "lib/gcc/current" gcc-prefix)))
        (push gcc-lib-current paths)

        ;; Find apple-darwin directory.
        (let* ((default-directory gcc-lib-current)
               (arch-dirs (file-expand-wildcards "gcc/*-apple-darwin*/*[0-9]")))
          (when arch-dirs
            (push (expand-file-name
                   (car (sort arch-dirs #'string>)))
                  paths))))

      ;; Get libgccjit paths
      (let* ((jit-prefix (string-trim
                          (shell-command-to-string
                           (concat brew-bin " --prefix libgccjit"))))
             (jit-lib-current (expand-file-name "lib/gcc/current" jit-prefix)))
        (push jit-lib-current paths)))

    (nreverse paths)))

(defun setup-macos-native-comp-library-paths ()
  "Set up LIBRARY_PATH for native compilation on macOS.
Includes Homebrew GCC paths and CommandLineTools SDK libraries."
  (let* ((existing-paths (split-string (or (getenv "LIBRARY_PATH") "") ":" t))
         (gcc-paths (homebrew-gcc-paths))
         (clt-paths '("/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib"))
         (unique-paths (delete-dups
                        (append existing-paths gcc-paths clt-paths))))

    (setenv "LIBRARY_PATH" (mapconcat #'identity unique-paths ":"))))

;; Set up library paths for native compilation on macOS.
(when (eq system-type 'darwin)
  (setup-macos-native-comp-library-paths))
```

It finds the `brew` executable, calls `brew --prefix gcc` and `brew --prefix libgccjit` to find the package root paths, and then does a wildcard search for `*-apple-darwin*/*` within GCC to find the relevant versioned directory name.

**Comment by jimeh** [comment] 2025-03-28 20:25
@d12frosted What do you think of maybe including the above snippet (or something similar) as a patch in emacs-plus?

I've got something similar in my self-contained [nightly builds](https://github.com/jimeh/build-emacs-for-macos), where I add a custom `lisp/macos-startup.el` file to the source tree, and modify `loadup.el` to load it right after `startup.el`.

In my builds, `macos-startup.el` is geared towards finding GCC and libgccjit that gets embedded into the Emacs.app bundle, something similar for emacs-plus would obviously need to be geared towards finding GCC and libgccjit via Homebrew.

**Comment by queitsch** [comment] 2025-03-29 10:04
@jimeh oh wow, thanks. You're going to make me unretire an Intel Mac to test, even :)

Also hadn't stumbled over `file-expand-wildcards` yet, very neat.

**Comment by AjaiKN** [comment] 2025-04-03 07:20
Thanks @jimeh! That snippet seems to work for me too.

**Comment by d12frosted** [comment] 2025-04-03 07:37
@jimeh I am very open to including the above snippet 🔥 PR is more than welcome 🙏
