### ISSUE TITLE
Could not install @28 --with-native-comp (M1 Pro, macOS 12.0.1)

### ISSUE THREAD

**Issue by brow** [d12frosted/homebrew-emacs-plus#432] opened 2021-12-22 21:23 UTC
Please make sure to follow these steps (and mark the checkboxes):

- [x] run `brew update` and try to reproduce the issue again
- [x] run `brew doctor`, fix all issues and try to reproduce your issue again
- [x] run `brew config` and `brew doctor` and include their output

## What you were trying to do

Install Emacs 28 `--with-native-comp` on MacBook 16" M1 Pro running macOS Monterey.

## What happened (include command output)

<pre>
brew install emacs-plus@28 --with-nobu417-big-sur-icon --with-native-comp
</pre>

Build failed with:
<details>
  <summary>Command output</summary>
  <pre>
==> Cloning https://github.com/emacs-mirror/emacs.git
Cloning into '/Users/tombrow/Library/Caches/Homebrew/emacs-plus@28--git'...
==> Checking out branch emacs-28
Already on 'emacs-28'
Your branch is up to date with 'origin/emacs-28'.
==> Installing emacs-plus@28 from d12frosted/emacs-plus
==> Patching
==> Applying fix-window-role.patch
patching file src/nsterm.m
Hunk #1 succeeded at 8602 (offset -166 lines).
==> Applying system-appearance.patch
patching file src/frame.h
patching file src/nsfns.m
Hunk #1 succeeded at 1315 (offset 59 lines).
patching file src/nsterm.m
Hunk #1 succeeded at 1878 (offset -11 lines).
Hunk #2 succeeded at 5389 (offset -6 lines).
Hunk #3 succeeded at 5635 (offset -6 lines).
Hunk #4 succeeded at 5685 (offset -6 lines).
Hunk #5 succeeded at 5911 (offset -6 lines).
Hunk #6 succeeded at 8935 (offset 33 lines).
Hunk #7 succeeded at 10091 (offset 33 lines).
==> ./autogen.sh
==> ./configure --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-plus@28
==> make
Last 15 lines from /Users/tombrow/Library/Logs/Homebrew/emacs-plus@28/03.make:
Loading cus-face (native compiled elisp)...
Loading faces (native compiled elisp)...
Loading loaddefs.el (source)...
Loading button (native compiled elisp)...
Loading emacs-lisp/nadvice (native compiled elisp)...
Loading emacs-lisp/cl-preloaded (native compiled elisp)...
Loading obarray (native compiled elisp)...
Loading abbrev (native compiled elisp)...
Loading simple (native compiled elisp)...
Loading help (native compiled elisp)...
Loading jka-cmpr-hook (native compiled elisp)...
Loading epa-hook (native compiled elisp)...
Loading international/mule-cmds (native compiled elisp)...
Wrong type argument: consp, make[1]: *** [emacs.pdmp] Segmentation fault: 11
make: *** [src] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/d12frosted/homebrew-emacs-plus/issues

These open issues may also help:
Permission issues with emacs-plus running as a service https://github.com/d12frosted/homebrew-emacs-plus/issues/304
Need to set LIBRARY_PATH for emacs-plus@28 with --with-native-comp https://github.com/d12frosted/homebrew-emacs-plus/issues/378</pre>
</details>

## Output of `brew config`

<pre>
$ brew config
HOMEBREW_VERSION: 3.3.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 96137bc19e68398ebbb7033379df288cd8b9a3f9
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 15e7f288e4b97c75b32c75748df0daa3b60d1c77
Core tap last commit: 47 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: 10-core 64-bit westmere
Clang: 13.0.0 build 1300
Git: 2.32.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.0.1-x86_64
CLT: 13.2.0.0.1.1638488800
Xcode: 13.1
Rosetta 2: true
</pre>

## Output of `brew doctor`

<pre>
$ brew doctor
Your system is ready to brew.
</pre>

**Comment by brow** [comment] 2021-12-22 21:27
The error seems identical to that in #429:
```
Loading international/mule-cmds (native compiled elisp)...
Wrong type argument: consp, make[1]: *** [emacs.pdmp] Segmentation fault: 11
make: *** [src] Error 2
```

**Comment by brow** [comment] 2021-12-22 21:31
Following @gottwald's [workaround](https://github.com/d12frosted/homebrew-emacs-plus/issues/429#issuecomment-990374738), I removed `~/Library/Caches/Homebrew/emacs-plus@28--git` (but did not "pull it manually" because I'm not sure how to do that) before attempting the command a second time. However, the result was the same.

**Comment by thornjad** [comment] 2022-02-11 17:01
I previously experienced this error as well, but when I tried again today, I'm now able to install _@29_ with native-comp on my M1. I did not test with @28, but 29 seems alright now, if that's an option for anyone who runs into this.

**Comment by gitautas** [comment] 2022-03-11 08:28
I can confirm that I still cannot install @29 with native comp, hangs on pulling the emacs git repo.

**Comment by d12frosted** [comment] 2022-03-11 10:06
@gitautas glad it worked. I am currently located in mountains with bad internet connection and cloning takes a lot of time. Compiling emacs on master takes time, compiling with `native-comp` feature takes even more. On CI it's 15 and 25 minutes respectively. So yeah, patience is required.

---

Since people report that `native-comp` works on M1, I am going to close this issue. Feel free to contribute further to this thread. If needed, I will reopen.

**Closed by d12frosted** 2022-03-11 10:06 UTC
Labels: install error

**Comment by gitautas** [comment] 2022-03-11 10:08
Thanks for maintaining this repo.

Слава Україні
