### ISSUE TITLE
Could not install emacs-plus@28 on macOS

### ISSUE THREAD

**Issue by anildigital** [d12frosted/homebrew-emacs-plus#379] opened 2021-08-05 11:45 UTC
Please make sure to follow these steps (and mark the checkboxes):

- [x ] run `brew update` and try to reproduce the issue again
- [ x] run `brew doctor`, fix all issues and try to reproduce your issue again
- [ ]x run `brew config` and `brew doctor` and include their output

## What you were trying to do

Trying to install emacs-plus (with native comp)

`brew install emacs-plus@28 --with-native-comp --with-no-titlebar --with-no-frame-refocus`

## What happened (include command output)

```bash
 brew install emacs-plus@28 --with-native-comp --with-no-titlebar --with-no-frame-refocus
==> Installing emacs-plus@28 from d12frosted/emacs-plus
==> Cloning https://github.com/emacs-mirror/emacs.git
Updating /Users/anil/Library/Caches/Homebrew/emacs-plus@28--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 2d8c14d299 Fix M-n description in refcards
==> Patching
==> Applying no-titlebar.patch
patching file src/nsterm.m
Hunk #1 succeeded at 433 (offset -40 lines).
Hunk #2 FAILED at 1943.
Hunk #3 FAILED at 7497.
Hunk #4 FAILED at 7535.
3 out of 4 hunks FAILED -- saving rejects to file src/nsterm.m.rej

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/d12frosted/homebrew-emacs-plus/issues

These open issues may also help:
Need to set LIBRARY_PATH for emacs-plus@28 with --with-native-comp https://github.com/d12frosted/homebrew-emacs-plus/issues/378
Emacs-plus@28 with native comp crashes on MacOS 12/Monterey https://github.com/d12frosted/homebrew-emacs-plus/issues/361
Permission issues with emacs-plus running as a service https://github.com/d12frosted/homebrew-emacs-plus/issues/304
```

## Output of `brew config`

<pre>
HOMEBREW_VERSION: 3.2.6-34-g6bb3699
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6bb369916c9ac031e693264db6fd2b4ba09ffeed
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a4603e2a0b85d0f3301362838523b6c1890ac970
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: 192.168.59.3:0
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.32.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.5-x86_64
CLT: 12.5.1.0.1.1623191612
Xcode: N/A
</pre>

## Output of `brew doctor`

<pre>
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  ilmbase

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Applications/Postgres.app/Contents/Versions/13/bin/gdal-config

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libwx_baseu-3.1.6.0.0.dylib
  /usr/local/lib/libwx_baseu_net-3.1.6.0.0.dylib
  /usr/local/lib/libwx_baseu_xml-3.1.6.0.0.dylib
  /usr/local/lib/libwx_osx_cocoau_adv-3.1.6.0.0.dylib
  /usr/local/lib/libwx_osx_cocoau_aui-3.1.6.0.0.dylib
  /usr/local/lib/libwx_osx_cocoau_core-3.1.6.0.0.dylib
  /usr/local/lib/libwx_osx_cocoau_gl-3.1.6.0.0.dylib
  /usr/local/lib/libwx_osx_cocoau_html-3.1.6.0.0.dylib
  /usr/local/lib/libwx_osx_cocoau_media-3.1.6.0.0.dylib
  /usr/local/lib/libwx_osx_cocoau_propgrid-3.1.6.0.0.dylib
  /usr/local/lib/libwx_osx_cocoau_qa-3.1.6.0.0.dylib
  /usr/local/lib/libwx_osx_cocoau_ribbon-3.1.6.0.0.dylib
  /usr/local/lib/libwx_osx_cocoau_richtext-3.1.6.0.0.dylib
  /usr/local/lib/libwx_osx_cocoau_stc-3.1.6.0.0.dylib
  /usr/local/lib/libwx_osx_cocoau_webview-3.1.6.0.0.dylib
  /usr/local/lib/libwx_osx_cocoau_xrc-3.1.6.0.0.dylib

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  imath
  openexr
</pre>

**Comment by d12frosted** [comment] 2021-08-09 07:37
Duplicate of #376

**Closed by d12frosted** 2021-08-09 07:37 UTC
Labels: install error
