### ISSUE TITLE
Build failing with --HEAD (due to imagemagick)

### ISSUE THREAD

**Issue by aaronjensen** [d12frosted/homebrew-emacs-plus#161] opened 2019-12-23 14:46 UTC
Strangely, I was able to build yesterday, but not today. Here's where it crashes:

```
Loading /private/var/tmp/emacs-plus-20191223-29475-3w4xqb/lisp/replace.el (source)...
Loading /private/var/tmp/emacs-plus-20191223-29475-3w4xqb/lisp/emacs-lisp/tabulated-list.el (source)...
Loading /private/var/tmp/emacs-plus-20191223-29475-3w4xqb/lisp/buff-menu.el (source)...
Loading /private/var/tmp/emacs-plus-20191223-29475-3w4xqb/lisp/fringe.el (source)...
Loading /private/var/tmp/emacs-plus-20191223-29475-3w4xqb/lisp/emacs-lisp/regexp-opt.el (source)...
Loading /private/var/tmp/emacs-plus-20191223-29475-3w4xqb/lisp/image.el (source)...
make[1]: *** [bootstrap-emacs.pdmp] Segmentation fault: 11
make: *** [src] Error 2
```

I'm not able to build the revision I had built yesterday either, so it doesn't seem like it's an upstream issue. Maybe it's just my machine somehow?

**Comment by mbarton98** [comment] 2019-12-23 16:00
I get the same error on Mojave as of 2019-12-22, so it is not specific to Catalina.

**Comment by mbarton98** [comment] 2019-12-23 16:26
I just noticed that master is now version 28 and there is a release branch for 27.

Cut the emacs-27 release branch

**Comment by aaronjensen** [comment] 2019-12-23 17:03
I do not get the error when building manually from source, fwiw.

**Comment by d12frosted** [comment] 2019-12-24 11:47
Indeed, something is broken. It seems that one of the options doesn't work anymore. Will bisect which one.

**Comment by d12frosted** [comment] 2019-12-24 12:20
Yep, it builds if I comment out all the imagemagick stuff. So just add `--without-imagemagick@7` option along with `--HEAD` and you'll be fine.

Not sure what exactly is wrong with imagemagick.

**Comment by aaronjensen** [comment] 2019-12-24 16:20
Confirmed, works for me as well. Thanks.

**Comment by webframp** [comment] 2019-12-24 19:58
Confirmed as well, this worked for me:
```
brew install --fetch-HEAD emacs-plus --HEAD --with-no-titlebar --with-modern-icon --with-jansson --without-spacemacs-icon --without-imagemagick@7
```

**Comment by d12frosted** [comment] 2019-12-26 07:05
@webframp just curious, what is `--fetch-HEAD`?

**Comment by webframp** [comment] 2019-12-26 18:07
@d12frosted just an extra check to ensure I really get the latest:

```
        --HEAD                       If formula defines it, install the HEAD
                                     version, aka. master, trunk, unstable.
        --fetch-HEAD                 Fetch the upstream repository to detect if
                                     the HEAD installation of the formula is
                                     outdated. Otherwise, the repository's HEAD
                                     will only be checked for updates when a new
                                     stable or development version has been
                                     released.
```

**Comment by d12frosted** [comment] 2019-12-27 17:49
@webframp wow, didn't know about it. thanks!

Regarding the imagemagick - I didn't had a chance to check why it doesn't build. Will try to do it on weekends, but can't promise.

If someone knows what happened, please share your knowledge :)

**Comment by mbarton98** [comment] 2019-12-27 18:31
@d12frosted FYI, I ended up compiling it myself, but checked out the emacs-27 branch instead of master. Maybe you could try adding an option for emacs-27 in addition to staying on master? I only used the --fetch-head option to get the 27 features of json support to help with lsp-mode.

Thank you for maintaining this formula, it really helped introduce me to Emacs without getting locked into a very specific distribution like Spacemacs.

**Comment by d12frosted** [comment] 2019-12-28 07:44
> Maybe you could try adding an option for emacs-27 in addition to staying on master?

Yeah, I could add a `--devel` option. Hopefully will get some time tomorrow to play with it.

> Thank you for maintaining this formula, it really helped introduce me to Emacs without getting locked into a very specific distribution like Spacemacs.

Thank you for the kind words :smile_cat:

**Comment by d12frosted** [comment] 2019-12-29 11:23
Indeed, it builds on `emacs-27`. I've added a `devel` option, but for some reason it breaks all formula. If someone knows what's wrong with this definition (https://github.com/d12frosted/homebrew-emacs-plus/commit/6507d9fd32cbbd17542a1e4a5ea41c1ccd1b9bb1), I would be glad to know :)

**Comment by d12frosted** [comment] 2019-12-29 11:38
It seems that `devel` is not in favor anymore, so I decided to add a separate option for `emacs-27` branch called `--with-emacs-27-branch` in f33038c.

You can use it like this:

```
$ brew install emacs-plus --HEAD --with-emacs-27-branch
```

But I need to figure out why HEAD breaks. Will share any updates once I have them.

**Comment by d12frosted** [comment] 2019-12-29 12:04
So I found [a thread](https://lists.gnu.org/archive/html/emacs-devel/2019-12/msg00643.html) on the mailing list. It seems that the first patch is already in master (https://github.com/emacs-mirror/emacs/commit/ee12c421b61218a868712f66b0176c451e20717e). And it builds. Actually, thanks to this patch `emacs-27` branch also builds 😸 

It seems that there will be another patch related to imagemagick (see the thread), but since now everything works - gonna close this issue.

P. S. leaving `--with-emacs-27-branch`, hopefully it will help testing the release branch haha

**Closed by d12frosted** 2019-12-29 12:04 UTC

**Comment by d12frosted** [comment] 2019-12-29 13:20
Regarding the red master - I've moved to GitHub actions (anyways was planning to do it). And going to check if `--HEAD` will work here (on Travis I could not build the `--HEAD`). See https://github.com/d12frosted/homebrew-emacs-plus/pull/164 for status.
